sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockernagbattula/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockernagbattula/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-705597486007"
  bucket_path: "docker"
  on:
    branches: # ← new!
      only: # ← new!
        - master # ← new!
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
